/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  DateString,
  IPlusConfig,
} from './components/datepicker-plus/datepicker-plus';

export namespace Components {
  interface DatepickerPlus {
    'plusConfig': IPlusConfig;
  }
}

declare global {


  interface HTMLDatepickerPlusElement extends Components.DatepickerPlus, HTMLStencilElement {}
  var HTMLDatepickerPlusElement: {
    prototype: HTMLDatepickerPlusElement;
    new (): HTMLDatepickerPlusElement;
  };
  interface HTMLElementTagNameMap {
    'datepicker-plus': HTMLDatepickerPlusElement;
  }
}

declare namespace LocalJSX {
  interface DatepickerPlus extends JSXBase.HTMLAttributes<HTMLDatepickerPlusElement> {
    'onOnDateSelect'?: (event: CustomEvent<DateString[]>) => void;
    'onOnDeselect'?: (event: CustomEvent<DateString[]>) => void;
    'onOnHighlight'?: (event: CustomEvent<DateString[]>) => void;
    'onOnHighlightClear'?: (event: CustomEvent<void>) => void;
    'onOnRangeSelect'?: (event: CustomEvent<DateString[]>) => void;
    'plusConfig'?: IPlusConfig;
  }

  interface IntrinsicElements {
    'datepicker-plus': DatepickerPlus;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


